language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6S (10.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
  - gem install xcpretty -N
script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild -project Brisk.xcodeproj -scheme "Brisk" -sdk "iphonesimulator10.3"
    -destination "OS=10.3,name=iPhone 6S" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - pod lib lint --quick
